### ISSUE TITLE
Работа с поиском

### ISSUE THREAD

**Issue by secretdoctrine** [secretdoctrine/Secret-Doctrine-site#15]
Необходимо реализовать поиск в выложенных книгах по ключевому слову или фразе.
Поиск может осуществляться по выбранной одной или нескольким книгам, разделам или библиотеке целиком. По умолчанию поиск происходит в текущем разделе/книге.
Результаты поиска могут отображаться двумя способами:
1. списком сниппетов, в которых указывается название книги, название или номер страницы, фрагмент найденного текста с выделенными поисковыми словами и прямая ссылка на страницу на сайте.
2. списком полноразмерных изображений найденных страниц, с выделенными на них поисковыми словами. Так же для каждой найденной страницы следует указывать название книги, название или номер страницы и ссылку на данную страницу на сайте.
При переходе по ссылке на страницу из результатов поиска желательно сохранять выделение поисковых слов.

Так же желательно иметь возможность сохранять в один клик из результатов поиска выбранную страницу в формате pdf или же все результаты поиска в виде zip архива страниц в формате pdf. Название каждого сохраненного файла при этом должно содержать название книги и номер страницы.

**Comment by HelgaOR** [comment]
Также предлагаю выводить отдельно результаты "книг, в которых найдены ключевые слова", с возможностью перехода на них и показа результатов этого же поиска конкретно по книге.

**Comment by HelgaOR** [comment]
На данный момент осталось:

1. Вкрутить подсветку найденного на страницах целиком
2. Вкрутить дерево в поиск
3. Добавить блок с книгами с результатами
4. Сверстать кнопки навигации по соседним страницам.

**Comment by HelgaOR** [comment]
Последний пункт вынесен в отдельный баг
