### ISSUE TITLE
Разобраться, куда вывести и выводить ли вообще ссылку "Где приобрести книги"

### ISSUE THREAD

**Issue by HelgaOR** [secretdoctrine/Secret-Doctrine-site#16]
Сейчас она в "книгах", но от этого раздела решили избавиться. Надо понять, что с ней делать.

**Comment by secretdoctrine** [comment]
ссылка на нее есть еще из Библиотеки (кнопка Заказать). вот туда ее и надо деть.

**Comment by HelgaOR** [comment]
То есть отдельная ссылка на каждой книге?
