### ISSUE TITLE
Разобраться с упорядочиванием категорий и книг в дереве

### ISSUE THREAD

**Issue by HelgaOR** [secretdoctrine/Secret-Doctrine-site#29]
1. Категории и книги в дереве могут идти в любом порядке. Порядок будет устанавливаться в админке путем перетаскивания пунктов в дереве. При этом может быть такое, что в категории сначала идет книга, потом - категория с книгами, а потом еще одна или несколько книг.

2. Плашки просмотра информации о книгах должны выводиться в том же сквозном порядке, как и в дереве. То есть, если в дереве идет книга, категория и потом снова книги, то нужно выводить плашку первой книги, потом плашки всех книг из вложенной категории, потом плашки всех последующих книг.

ИЛИ

Сделать как на старом сайте, то есть выводить только один слой дерева, при этом для категории выводить плашку информации о категории с кнопкой "войти в раздел".

**Comment by secretdoctrine** [comment]
Необходимо  сделать как на старом сайте, только один слой дерева. Иначе пользователь потонет в информации, особенно если категорий несколько.

**Comment by HelgaOR** [comment]
Ок, значит, по второму варианту.
