### ISSUE TITLE
Разобраться с отступами в конвертируемых файлах

### ISSUE THREAD

**Issue by HelgaOR** [secretdoctrine/Secret-Doctrine-site#46]
Сейчас подсветка в поиске (да и выделение текста) заметно съезжает.

Это особенно заметно на:

1. курсиве
2. коротких строках с отступом слева
3. нестандартном по ширине шрифте

Надо попробовать починить.

**Comment by Shurf** [comment]
С rangy все работает на немодифицированной версии конвертера
