### ISSUE TITLE
Скачиваемый архив с результатами поиска

### ISSUE THREAD

**Issue by secretdoctrine** [secretdoctrine/Secret-Doctrine-site#50]
Поработать с названием скачиваемого архива. Возможно, стоит в качестве имени указывать текущую дату.
И посмотреть, что происходит со скачиваемым архивом – шеф не смог открыть скачанные файлы в Adobe, только в Reader.

**Comment by HelgaOR** [comment]
Дата добавлена. Что там с ридером, надо разбираться отдельно
